export const heroStyles = {
  // Fill the viewport minus navbar height (4rem) and center content
  section: "bg-gradient-to-br from-gray-50 via-white to-blue-50 min-h-[calc(100svh-4rem)] flex items-center",
  // Responsive padding scaled to viewport height
  container: "mx-auto max-w-7xl px-4 py-[clamp(2rem,6vh,4rem)]",
  stack: "flex flex-col items-center gap-6 text-center isolate",
  title: "relative z-0 max-w-4xl text-5xl font-bold leading-[1.15] tracking-tight text-gray-900 md:text-6xl lg:text-7xl",
  titleLine: "block leading-[1.08]",
  highlightStudy: "font-semibold text-[#ff0000]",
  underlineCallout: "mt-2 block underline decoration-black decoration-[6px] underline-offset-8",
  sub: "mt-4 max-w-2xl text-lg font-normal text-gray-600 md:text-xl",
  ctas: "mt-6 flex flex-col gap-4 sm:flex-row",
  primary: "inline-flex items-center justify-center rounded-md bg-gray-900 px-6 py-3 text-lg font-semibold text-white shadow-sm hover:bg-black",
  secondary: "inline-flex items-center justify-center rounded-md border border-gray-300 px-6 py-3 text-lg font-medium text-gray-800 hover:bg-gray-50",
  mockWrap: "mt-16 w-full max-w-7xl",
  card: "overflow-hidden rounded-2xl border-gray-200 shadow-2xl",
  mockGrid: "grid grid-cols-1 gap-0 md:grid-cols-2",
  chatPane: "border-r border-gray-100 bg-white p-6",
  chatTitle: "mb-4 text-left text-sm font-semibold text-gray-700",
  chatMessages: "space-y-3",
  chatRowLeft: "flex justify-start",
  chatRowRight: "flex justify-end",
  leftBubble: "max-w-[80%] rounded-2xl rounded-tl-sm bg-gray-100 px-4 py-3 text-sm text-gray-900",
  rightBubble: "max-w-[80%] rounded-2xl rounded-tr-sm bg-blue-600 px-4 py-3 text-sm text-white",
  calPane: "bg-white p-6",
  calHeader: "mb-3 text-left text-sm font-semibold text-gray-700",
  calDaysRow: "grid grid-cols-7 gap-1 text-left text-xs text-gray-500",
  dayName: "text-center",
  calGrid: "mt-2 grid grid-cols-7 gap-1",
  calCell: "relative h-40 rounded-md border border-gray-100 bg-gray-50",
  eventTeal: "absolute left-0 right-0 top-6 rounded-md border-l-4 border-teal-400 bg-teal-100 px-3 py-1.5 text-xs font-semibold text-gray-800 shadow-sm whitespace-nowrap",
  eventYellow: "absolute left-0 right-0 top-14 rounded-md border-l-4 border-yellow-400 bg-yellow-100 px-3 py-1.5 text-xs font-semibold text-gray-800 shadow-sm whitespace-nowrap",
  highlightSec: "inline px-1 rounded-[0.15em] text-gray-900 bg-[linear-gradient(transparent_58%,theme(colors.green.200)/0.7_0)]",
  highlightHours: "inline px-2 rounded-[0.15em] text-gray-900 bg-gray-200",
}
