export const navbarStyles = {
  header: "sticky top-0 z-50 w-full border-b border-gray-200 bg-white/80 backdrop-blur-md",
  container: "mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8",
  row: "flex items-center gap-8",
  brand: "text-2xl font-bold tracking-tight text-gray-900",
  navList: "hidden lg:flex",
  navUl: "flex items-center gap-8",
  navLink: "text-sm font-medium text-gray-600 transition-colors hover:text-gray-900",
  ctas: "hidden items-center gap-2 lg:flex",
  signIn: "inline-flex h-9 items-center rounded-md px-4 text-sm font-medium text-gray-700 hover:bg-gray-100",
  getStarted: "inline-flex h-9 items-center rounded-md bg-gray-900 px-4 text-sm font-semibold text-white shadow-sm hover:bg-black",
  mobile: "lg:hidden",
  mobileTrigger: "inline-flex h-9 w-9 items-center justify-center rounded-md border border-gray-200 hover:bg-gray-50",
  sheetBody: "mt-6 space-y-6",
  sheetLink: "block text-base font-medium text-gray-700 hover:text-gray-900",
  sheetSignIn: "block rounded-md px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100",
  sheetGetStarted: "mt-2 block rounded-md bg-gray-900 px-3 py-2 text-sm font-semibold text-white hover:bg-black",
}
