export const pricingStyles = {
  section: "bg-gradient-to-b from-gray-50 to-white py-24",
  container: "mx-auto max-w-6xl px-4",
  title: "text-center text-3xl font-bold md:text-4xl",
  sub: "mb-16 mt-2 text-center text-lg text-gray-600",
  grid: "grid grid-cols-1 gap-8 md:grid-cols-3",
  card: "relative h-full rounded-2xl border-2 border-gray-200 bg-white p-0 transition-shadow hover:shadow-xl",
  cardOuterGradient: "relative h-full rounded-2xl bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 p-[2px]",
  cardInner: "relative flex h-full flex-col rounded-[14px] bg-white p-8",
  badge: "absolute -top-4 left-1/2 -translate-x-1/2 rounded-full bg-blue-600 px-4 py-1 text-sm font-semibold text-white",
  planTitle: "text-2xl font-bold",
  price: "mt-4 text-4xl font-bold",
  per: "ml-1 text-base font-medium text-gray-600",
  note: "mt-2 text-sm text-gray-600",
  features: "mt-6 space-y-3 text-sm text-gray-700",
  bullet: "mt-1 inline-block h-1.5 w-1.5 rounded-full bg-gray-400",
  ctaWrap: "mt-auto pt-6",
  ctaOutline: "inline-flex w-full items-center justify-center rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-900 hover:bg-gray-50",
  ctaGradient: "group relative inline-flex w-full items-center justify-center rounded-md p-[2px] bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500",
  ctaGradientInner: "w-full rounded-md bg-white px-4 py-2 text-sm font-semibold text-gray-900 [background:linear-gradient(white,white)] group-hover:bg-gray-50",
}
