-- Final Lean Schema Migration
-- Consolidates all tables with minimal design

-- Drop old tables if they exist (from previous migrations)
DROP TABLE IF EXISTS public.learning_history CASCADE;
DROP TABLE IF EXISTS public.user_subjects CASCADE;

-- 1. USERS TABLE (mostly unchanged, removed subjects)
-- No changes needed, just ensure it exists

-- 2. TASKS TABLE
-- Add missing columns if they don't exist
ALTER TABLE public.tasks
    ADD COLUMN IF NOT EXISTS title TEXT,
    ADD COLUMN IF NOT EXISTS estimated_duration INTEGER,
    ADD COLUMN IF NOT EXISTS difficulty INTEGER CHECK (difficulty >= 1 AND difficulty <= 10),
    ADD COLUMN IF NOT EXISTS subject TEXT,
    ADD COLUMN IF NOT EXISTS priority TEXT CHECK (priority IN ('high', 'medium', 'low')),
    ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT timezone('utc', now());

-- Remove old SM2 columns from tasks (if they exist)
ALTER TABLE public.tasks
    DROP COLUMN IF EXISTS last_reviewed_at,
    DROP COLUMN IF EXISTS next_review_date,
    DROP COLUMN IF EXISTS easiness_factor,
    DROP COLUMN IF EXISTS repetition_count;

-- Create index on subject
CREATE INDEX IF NOT EXISTS idx_tasks_subject ON public.tasks(subject) WHERE subject IS NOT NULL;

-- 3. CALENDAR_EVENTS TABLE
ALTER TABLE public.calendar_events
    ADD COLUMN IF NOT EXISTS color_hex TEXT,
    ADD COLUMN IF NOT EXISTS fixed BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS subject TEXT;

-- Update event_type constraint to include all types
ALTER TABLE public.calendar_events
    DROP CONSTRAINT IF EXISTS calendar_events_event_type_check;

ALTER TABLE public.calendar_events
    ADD CONSTRAINT calendar_events_event_type_check 
    CHECK (event_type IN ('study', 'review', 'break', 'user_event'));

-- Rename colour_hex to color_hex if it exists
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'calendar_events' 
        AND column_name = 'colour_hex'
    ) THEN
        ALTER TABLE public.calendar_events RENAME COLUMN colour_hex TO color_hex;
    END IF;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_calendar_events_user_id ON public.calendar_events(user_id);
CREATE INDEX IF NOT EXISTS idx_calendar_events_start_time ON public.calendar_events(start_time);
CREATE INDEX IF NOT EXISTS idx_calendar_events_task_id ON public.calendar_events(task_id) WHERE task_id IS NOT NULL;

-- 4. REVIEW_SESSIONS TABLE (keep minimal)
-- Already exists from previous migration, just ensure it's correct
CREATE TABLE IF NOT EXISTS public.review_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    scheduled_date TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'skipped')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    completed_at TIMESTAMPTZ
);

-- Drop old columns if they exist
ALTER TABLE public.review_sessions
    DROP COLUMN IF EXISTS review_type,
    DROP COLUMN IF EXISTS source_task_ids;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_review_sessions_user_id ON public.review_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_review_sessions_scheduled_date ON public.review_sessions(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_review_sessions_status ON public.review_sessions(status);

-- 5. SETTINGS TABLE (formerly energy_profiles)
-- Rename energy_profiles to settings if needed
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'energy_profiles'
    ) THEN
        ALTER TABLE public.energy_profiles RENAME TO settings;
    END IF;
END $$;

-- Create settings table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.settings (
    user_id BIGINT PRIMARY KEY,
    subjects TEXT[],
    wake_time TIME NOT NULL,
    sleep_time TIME NOT NULL,
    max_study_duration INTEGER NOT NULL,
    min_study_duration INTEGER NOT NULL,
    short_break INTEGER DEFAULT 15,
    long_break INTEGER DEFAULT 30,
    long_study_threshold INTEGER DEFAULT 90,
    energy_levels JSONB NOT NULL,
    onboarding_complete BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- Add subjects column if it doesn't exist
ALTER TABLE public.settings
    ADD COLUMN IF NOT EXISTS subjects TEXT[];

-- 6. FEEDBACK TABLE
CREATE TABLE IF NOT EXISTS public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_feedback_user_id ON public.feedback(user_id);
CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON public.feedback(created_at);

-- Enable RLS on new tables
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- RLS Policies for feedback
DROP POLICY IF EXISTS "Users can create own feedback" ON public.feedback;
CREATE POLICY "Users can create own feedback"
    ON public.feedback FOR INSERT
    WITH CHECK (auth.uid()::text = user_id::text);

DROP POLICY IF EXISTS "Users can view own feedback" ON public.feedback;
CREATE POLICY "Users can view own feedback"
    ON public.feedback FOR SELECT
    USING (auth.uid()::text = user_id::text);

-- Update RLS policies for review_sessions if not already set
ALTER TABLE public.review_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own review sessions" ON public.review_sessions;
CREATE POLICY "Users can manage own review sessions"
    ON public.review_sessions FOR ALL
    USING (auth.uid()::text = user_id::text);

-- Set default for user manual events to be fixed
-- This is a comment for application logic, not enforced at DB level
-- Application should set fixed = TRUE for:
-- 1. User-created events (source = 'user')
-- 2. Review events (event_type = 'review')
-- 3. Events targeted for rescheduling

COMMENT ON COLUMN public.calendar_events.fixed IS 'TRUE = cannot be rescheduled (user events, reviews). FALSE = flexible (study sessions)';
COMMENT ON COLUMN public.settings.subjects IS 'Array of subject names from onboarding. Used for UI and interleaving.';
COMMENT ON TABLE public.review_sessions IS 'SM2 spaced repetition schedule. Creates fixed calendar_events on task completion.';
