-- Learning Science Enhancement: Add tables and columns for spaced repetition, interleaving, and active recall

-- 1. Create user_subjects table for subject management and interleaving
CREATE TABLE IF NOT EXISTS public.user_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    subject_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE(user_id, subject_name)
);

-- Index for fast lookups by user
CREATE INDEX IF NOT EXISTS idx_user_subjects_user_id ON public.user_subjects(user_id);

-- 2. Create learning_history table for tracking review performance (SM2 algorithm)
CREATE TABLE IF NOT EXISTS public.learning_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    review_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    quality_rating INTEGER NOT NULL CHECK (quality_rating >= 0 AND quality_rating <= 5),
    interval_days INTEGER NOT NULL,
    easiness_factor FLOAT NOT NULL,
    repetition_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_learning_history_user_id ON public.learning_history(user_id);
CREATE INDEX IF NOT EXISTS idx_learning_history_task_id ON public.learning_history(task_id);
CREATE INDEX IF NOT EXISTS idx_learning_history_review_date ON public.learning_history(review_date);

-- 3. Create review_sessions table for scheduled review events
CREATE TABLE IF NOT EXISTS public.review_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    task_id BIGINT,
    scheduled_date TIMESTAMPTZ NOT NULL,
    review_type TEXT NOT NULL CHECK (review_type IN ('spaced_repetition', 'active_recall', 'interleaving')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'skipped')),
    source_task_ids JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    completed_at TIMESTAMPTZ
);

-- Indexes for querying upcoming reviews
CREATE INDEX IF NOT EXISTS idx_review_sessions_user_id ON public.review_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_review_sessions_scheduled_date ON public.review_sessions(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_review_sessions_status ON public.review_sessions(status);

-- 4. Add learning science columns to tasks table
ALTER TABLE IF EXISTS public.tasks
    ADD COLUMN IF NOT EXISTS subject TEXT,
    ADD COLUMN IF NOT EXISTS last_reviewed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS next_review_date TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS easiness_factor FLOAT DEFAULT 2.5,
    ADD COLUMN IF NOT EXISTS repetition_count INTEGER DEFAULT 0;

-- Index for subject-based queries (for interleaving)
CREATE INDEX IF NOT EXISTS idx_tasks_subject ON public.tasks(subject) WHERE subject IS NOT NULL;

-- Index for review scheduling queries
CREATE INDEX IF NOT EXISTS idx_tasks_next_review_date ON public.tasks(next_review_date) WHERE next_review_date IS NOT NULL;

-- 5. Add RLS policies (Row Level Security)
-- Note: Using text comparison since auth.uid() returns UUID, not BIGINT

-- user_subjects policies
ALTER TABLE public.user_subjects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own subjects" ON public.user_subjects;
CREATE POLICY "Users can view their own subjects"
    ON public.user_subjects FOR SELECT
    USING (auth.uid()::text = user_id::text);

DROP POLICY IF EXISTS "Users can insert their own subjects" ON public.user_subjects;
CREATE POLICY "Users can insert their own subjects"
    ON public.user_subjects FOR INSERT
    WITH CHECK (auth.uid()::text = user_id::text);

DROP POLICY IF EXISTS "Users can delete their own subjects" ON public.user_subjects;
CREATE POLICY "Users can delete their own subjects"
    ON public.user_subjects FOR DELETE
    USING (auth.uid()::text = user_id::text);

-- learning_history policies
ALTER TABLE public.learning_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own learning history" ON public.learning_history;
CREATE POLICY "Users can view their own learning history"
    ON public.learning_history FOR SELECT
    USING (auth.uid()::text = user_id::text);

DROP POLICY IF EXISTS "Users can insert their own learning history" ON public.learning_history;
CREATE POLICY "Users can insert their own learning history"
    ON public.learning_history FOR INSERT
    WITH CHECK (auth.uid()::text = user_id::text);

-- review_sessions policies
ALTER TABLE public.review_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own review sessions" ON public.review_sessions;
CREATE POLICY "Users can view their own review sessions"
    ON public.review_sessions FOR SELECT
    USING (auth.uid()::text = user_id::text);

DROP POLICY IF EXISTS "Users can manage their own review sessions" ON public.review_sessions;
CREATE POLICY "Users can manage their own review sessions"
    ON public.review_sessions FOR ALL
    USING (auth.uid()::text = user_id::text);

