# models.py
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text, Float
from api.database import Base
from datetime import datetime, timezone

def utc_now_naive():
    """Get current UTC time as naive datetime for database storage"""
    return datetime.now(timezone.utc).replace(tzinfo=None)

class Task(Base):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    topic = Column(String, nullable=False)
    estimated_minutes = Column(Integer, nullable=False)
    difficulty = Column(Integer, default=3)  # 1=easy, 5=hard
    due_date = Column(DateTime, nullable=False)  # required: all tasks must have due dates
    description = Column(Text, nullable=True)  # detailed description
    source_text = Column(Text, nullable=True)  # original text from brain dump
    confidence_score = Column(Float, default=1.0)  # AI confidence in task extraction
    status = Column(String, default="unscheduled")  # unscheduled, scheduled, completed, missed
    brain_dump_id = Column(Integer, ForeignKey("brain_dumps.id"), nullable=True)
    last_studied = Column(DateTime, nullable=True)
    review_count = Column(Integer, default=0)
    scheduled_start = Column(DateTime, nullable=True)  # when task is scheduled
    scheduled_end = Column(DateTime, nullable=True)  # when task ends

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, nullable=False)
    name = Column(String, nullable=True)
    # external identity link (Google/OpenID subject)
    google_user_id = Column(String, nullable=True)
    # store hashed passwords if needed
    hashed_password = Column(String, nullable=True)
    created_at = Column(DateTime, default=utc_now_naive)
    # timezone for user's local time (e.g., "America/Los_Angeles", "UTC", "Asia/Tokyo")
    timezone = Column(String, default="UTC")
    # subscription fields
    subscription_plan = Column(String, default="free")  # free, pro, unlimited
    credits_used = Column(Integer, default=0)  # cumulative credits used
    subscription_status = Column(String, default="active")  # active, cancelled
    subscription_start_date = Column(DateTime, default=utc_now_naive)
    subscription_end_date = Column(DateTime, nullable=True)
    # Stripe linking (optional)
    stripe_customer_id = Column(String, nullable=True)
    stripe_subscription_id = Column(String, nullable=True)

class EnergyProfile(Base):
    __tablename__ = "energy_profiles"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    due_date_days = Column(Integer, default=7)  # days to add when defaulting due dates
    wake_time = Column(Integer, default=7)  # hour
    sleep_time = Column(Integer, default=23)  # hour
    max_study_duration = Column(Integer, default=180)  # minutes
    min_study_duration = Column(Integer, default=30)  # minutes
    # energy levels stored as JSON string: {"7": 6, "8": 7, ...}
    energy_levels = Column(Text, nullable=True)

class CalendarEvent(Base):
    __tablename__ = "calendar_events"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    start_time = Column(DateTime, nullable=False)
    end_time = Column(DateTime, nullable=False)
    event_type = Column(String, default="study")  # study, rest, break
    source = Column(String, default="user")  # user, system (system = auto-generated by scheduler)
    task_id = Column(Integer, ForeignKey("tasks.id", ondelete="CASCADE"), nullable=True)  # link to task if study session
    created_at = Column(DateTime, default=utc_now_naive)
    updated_at = Column(DateTime, default=utc_now_naive, onupdate=utc_now_naive)

class BrainDump(Base):
    """raw user input before AI processing"""
    __tablename__ = "brain_dumps"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    raw_text = Column(Text, nullable=False)
    attached_files = Column(Text, nullable=True)  # JSON array of file paths
    processing_status = Column(String, default="pending")  # pending, processing, completed, failed
    created_at = Column(DateTime, default=utc_now_naive)
    processed_at = Column(DateTime, nullable=True)
